# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['deploy_spot.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'boto3',
        'botocore',
        'botocore.retryhandler', 
        'botocore.vendored',
        'rich',
        'rich.console',
        'rich.table',
        'rich.panel',
        'rich.progress',
        'aiosqlite',
        'aiofiles',
        'yaml',
        'sqlite3',
        'asyncio',
        'concurrent.futures',
        'json',
        'pathlib',
        'datetime',
        'uuid',
        'tarfile',
        'gzip',
        'io',
        'base64',
        'csv',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Exclude modules we don't need to reduce size and startup time
        'tkinter',
        'matplotlib',
        'IPython',
        'notebook',
        'jupyter',
        'pandas',
        'numpy',
        'scipy',
        'PIL',
        'Pillow',
        'opencv',
        'cv2',
        'tornado',
        'flask',
        'django',
        'requests_oauthlib',
        'oauthlib',
        'setuptools',
        'distutils',
        'pkg_resources',
    ],
    noarchive=False,
    optimize=2,  # Higher optimization level
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='aws-spot-deployer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,  # Strip symbols to reduce size
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)