version: '3.8'

x-common-env: &common-env
  BACALHAU_DISABLEANALYTICS: "true"
  LOG_LEVEL: "${LOG_LEVEL:-info}"

services:
  bacalhau-compute:
    image: ghcr.io/bacalhau-project/bacalhau:latest
    container_name: bacalhau-compute
    hostname: "compute-${HOSTNAME:-node}"
    command: serve -c /etc/bacalhau/config.yaml
    environment:
      <<: *common-env
    network_mode: "host"
    restart: unless-stopped
    volumes:
      # Configuration
      - /etc/bacalhau/config.yaml:/etc/bacalhau/config.yaml:ro

      # Docker socket for job execution
      - /var/run/docker.sock:/var/run/docker.sock

      # Data directories
      - /bacalhau_data:/bacalhau_data
      - /bacalhau_node:/bacalhau_node

      # Sensor data access (read-only for Bacalhau jobs)
      - /opt/sensor/data:/opt/sensor/data:ro
      - /opt/sensor/exports:/opt/sensor/exports:ro

      # Temporary space
      - /tmp:/tmp

      # AWS credentials for S3 access in jobs
      - /root/.aws:/root/.aws:ro
      - /home/ubuntu/.aws:/home/bacalhau/.aws:ro

    healthcheck:
      test: ["CMD", "bacalhau", "version"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

    ulimits:
      nofile:
        soft: 65536
        hard: 65536

    labels:
      - "com.bacalhau.service=compute"
      - "com.bacalhau.deployment=skypilot"
