name: Create Version Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Create and push tag
      run: |
        VERSION="v${{ inputs.version }}"

        # Check if tag already exists
        if git tag --list | grep -q "^${VERSION}$"; then
          echo "Tag ${VERSION} already exists!"
          exit 1
        fi

        # Create annotated tag
        git tag -a "${VERSION}" -m "Release ${VERSION}"

        # Push the tag
        git push origin "${VERSION}"

        echo "Successfully created and pushed tag ${VERSION}"
